### ISSUE TITLE
[Algorithm] Obtaining the Subject Department of given Subject.

### ISSUE THREAD

**Issue by Rushyanth111** [Rushyanth111/Semster-Stats#21]

**Comment by sugy17** [comment]
main_depts=['cs','ec','me','cv','is','tc']
try:
    pos=main_depts.index(SUbjectCode[2:4])
    subject belongs to main_depts[pos]
except NotFoundException :
    subject belomngs to basic sci dept

**Comment by sugy17** [comment]
```python3
main_depts=('ec','cs','tc',me','is','cv')
dept=SubjectCode[2:4]
if dept in main_depts:
   #Subject belongs to dept, i.e SubjectCode[2:4]
else:
    #Subject blongs to basic science
```

**Comment by Rushyanth111** [comment]
Not reliable, unfortunately. Departments may cease to exist, and things need to be more general.

**Comment by sugy17** [comment]
```
1.text=#extract text in between the digits
2.if text in DepartmentCodeDictionary.keys():
	#belongs to dept=>text
  else if text[-1]=='l' or text[-1]=='p':
	text=#get text without a trailing 'l' or 'p'
	if text in DepartmentCodeDictionary.keys():
		#belongs to dept=>text
	else:
		#belongs to basic science
  else :
       #bwelongs to basic science
```

The idea here is to check with an 'l' or 'p' first, as some dept codes consist of 'l' or 'p' in the end, and then check without an 'l' or 'p'.
'l' => lab and 'p' => project.

**Comment by Rushyanth111** [comment]
That would do.

**Comment by sugy17** [comment]
the get method can be used instead of in operator, dose the job in O(1).

**Comment by Rushyanth111** [comment]
It's a dict, it's already O(1). I'll mark this as Closed when I Implement the Algorithm.

**Comment by Rushyanth111** [comment]
5fb37b8df0646680f21f8e20b6dfbe0186423e49 Fixes it.
